tasks:
  - init: |
      echo 'TODO: build project'
    command: |
      export GITADD="https://9100-${GITPOD_WORKSPACE_URL##https://}" && cd compose && docker-compose up
ports:
  - port: 9100
    visibility: public
  - port: 3001
    visibility: public
