#
#       AUTHOR - Raman Sailopal
#
#       docker compose yml file for the YottaDB-Dashboard stack
#
version: "2"
services:
 fileman:
   image: docker.io/vistadataproject/nodevista999
   hostname: fileman
   ports:
      - 9330:9430 
      - 32:22 
      - 9100:9000 
      - 9331:8001
      - 8083:8083
      - 8082:8082
   volumes:
      - ../fmql:/home/fmqlput
   networks:
      - yottanet
   entrypoint: [ "/bin/bash", "-c", "cd /home/fmqlput && ./entrypoint.sh" ]

 react:
   image: docker.io/ubuntu
   hostname: react
   ports:
      - 3001:3000
   environment:
      - GITADD=$GITADD
      - ZIPADD=$ZIPADD
      - DEBIAN_FRONTEND="noninteractive"
   volumes:
      - ../react/package.json:/home/react/fileman/package.json
      - ../react/src:/home/react/fileman/src
      - ../react/public:/home/react/fileman/public
      - ../react/entrypoint:/home/entrypoint
   networks:
      - yottanet
   entrypoint: [ "/bin/bash", "-c", "cd /home/entrypoint && ./entrypoint.sh" ]

 zipapi:
   image: docker.io/ramb0/api-zip
   hostname: apizip
   ports:
      - 5000:5000
   volumes:
      - ../zip:/home/zip
   networks:
      - yottanet
   entrypoint: [ "/bin/bash", "-c", "cd /home/zip && ./entrypoint.sh" ]


networks:
    yottanet:
